# Generated by Django 3.0.6 on 2020-05-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_ratings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
    ]
